name: CI
on:
  push:
    branches:
      - master
jobs:
  run_tests:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Make envfile
        uses: ./
        with:
          envkey_DEBUG: false
          envkey_SOME_API_KEY: "123456abcdef"
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          some_other_variable: foobar
          directory: <directory_name>
          file_name: .env
          fail_on_empty: false
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Tests
        run: python manage.py test